school/apps/articles/urls.py
from django.urls import path

from . import views


app_name = 'articles'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('<int:article_id>/', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment')
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('articles/', include('articles.urls')),
	 path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

school/apps/articles/models.py
from django.db import models

class Article(models.Model):
	article_title = models.CharField('Названия статьи', max_length = 200 )
	article_text = models.TextField('Текст статьи')
	article_photo = models.ImageField('Фото статьи')
	pub_date = models.DateTimeField('дата публикации')

	def __str__(self):
		return self.article_title

	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('Автор статьи', max_length = 50)
	comment_text = models.CharField("Текст статьи", max_length = 200)


	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Коментарии'

school/apps/articles/views.py
from django.shortcuts import render

from .models import Article, Comment
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse


def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404('Статья не найдена')

	'''latest_comment_list = a.comment_set.order_by('-id')[:10]'''
	return render(request, 'articles/detail.html', {'article': a})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404('Статья не найдена')

	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

school/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>
<hr>


<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
	{% csrf_token %}
	<input type="text" required placeholder="Ваше имя" name="name"><br>
	<textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea></br>

	<button type="submit">Оставить комментарий</button>

</form>

{% endblock %}

school/templates/articles/list — копия.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
	{% csrf_token %}
	<input type="text" required placeholder="Ваше имя" name="name"><br>
	<textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea></br>

	<button type="submit">Оставить комментарий</button>

</form>

{% endblock %}

school/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

	{% if latest_articles_list %}

	{% for a in latest_articles_list %}
		<a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
	{% endfor %}

	{% else %}
	Статьи не найдены
	{% endif %}

{% endblock %}

school/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>
	{% block content %}{% endblock %}


</body>
</html>